StoreManagementSystem/Models/GoodQualityInspection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StoreManagementSystem.Models
{
    public class GoodQualityInspection
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Enter Sequene")]
        [StringLength(100)]
        public string Sequence { get; set; }

        public DateTime InspectionDate { get; set; }

        [ForeignKey("GRN")]
        public int GRNId { get; set; }

        [ForeignKey("User")]
        public int? CreatedBy { get; set; }

        public virtual GRNmanagement GRN { get; set; }
        public virtual User User { get; set; }
    }
}

StoreManagementSystem/Controllers/GoodQualityInspectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreManagementSystem.Models;

namespace StoreManagementSystem.Controllers
{
    public class GoodQualityInspectionsController : Controller
    {
        private SMSDbContext db = new SMSDbContext();

        // GET: GoodQualityInspections
        public ActionResult Index()
        {
            var goodQualityInspection = db.GoodQualityInspection.Include(g => g.GRN).Include(g => g.User);
            return View(goodQualityInspection.ToList());
        }

        // GET: GoodQualityInspections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodQualityInspection goodQualityInspection = db.GoodQualityInspection.Find(id);
            if (goodQualityInspection == null)
            {
                return HttpNotFound();
            }
            return View(goodQualityInspection);
        }

        #region GetExistingItem
        public ActionResult GetExistingItems()
        {
            string ItemName = Request["ItemName"];
            int GRNId = Convert.ToInt32(Request["GRNId"]);
            List<GRNDetails> ItemList = new List<GRNDetails>();
            if (String.IsNullOrWhiteSpace(ItemName))
            {
                ItemList = db.GRNDetails.Where(i => i.GRNId == GRNId).ToList();
            }
            else
            {
                ItemList = db.GRNDetails.Where(i => i.GRNId == GRNId && i.Item.Name.Contains(ItemName)).ToList();
            }
            return Json(ItemList, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region GetExistingStore
        public ActionResult GetExistingStores()
        {
            string StoreName = Request["StoreName"];
            List<Store> ItemList = new List<Store>();
            if (String.IsNullOrWhiteSpace(StoreName))
            {
                ItemList = db.Store.Where(i => i.Status == true).ToList();
            }
            else
            {
                ItemList = db.Store.Where(i => i.Status == true && i.Name.Contains(StoreName)).ToList();
            }
            return Json(ItemList, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region GetSelectedItems
        [AllowAnonymous]
        [HttpPost]
        public ActionResult GetSelectedItems()
        {
            if (Request["ItemId"].ToString() != "")
            {
                int ItemId = Convert.ToInt32(Request["ItemId"]);
                double ReceivedQuantity = Convert.ToDouble(Request["ReceivedQuantity"]);
                double QCPassedQuantity = Convert.ToDouble(Request["QCPassedQuantity"]);
                double RejectedQuantity = Convert.ToDouble(Request["RejectedQuantity"]);
                int StoreId = Convert.ToInt32(Request["StoreId"]);

                List<GQIInfo> ItemList = new List<GQIInfo>();
                ItemList = (List<GQIInfo>)Session["ItemList"];
                if (ItemList.Count() > 0)
                {
                    GQIInfo details = new GQIInfo();
                    details.Id = ItemList.Count() + 1;
                    details.ItemId = ItemId;
                    details.ReceivedQuantity = ReceivedQuantity;
                    details.QCPassedQuantity = QCPassedQuantity;
                    details.RejectedQuantity = RejectedQuantity;
                    details.StoreId = StoreId;
                    details.Item = db.Item.Find(ItemId);
                    details.Store = db.Store.Find(StoreId);
                    ItemList.Add(details);
                    Session["ItemList"] = ItemList;
                }
                else
                {
                    List<GQIInfo> ItemLst = new List<GQIInfo>();
                    GQIInfo details = new GQIInfo();
                    details.Id = 1;
                    details.Id = ItemList.Count() + 1;
                    details.ItemId = ItemId;
                    details.ReceivedQuantity = ReceivedQuantity;
                    details.QCPassedQuantity = QCPassedQuantity;
                    details.RejectedQuantity = RejectedQuantity;
                    details.StoreId = StoreId;
                    details.Item = db.Item.Find(ItemId);
                    details.Store = db.Store.Find(StoreId);
                    ItemLst.Add(details);
                    Session["ItemList"] = ItemLst;
                }
            }
            return Json(Session["ItemList"], JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult DeleteFromList()
        {
            int DetailsId = Convert.ToInt32(Request["DetailsId"]);
            List<GQIInfo> ItemLst = new List<GQIInfo>();
            ItemLst = (List<GQIInfo>)Session["ItemList"];
            for (int i = 0; i < ItemLst.Count; i++)
            {
                if (ItemLst[i].Id == DetailsId)
                {
                    ItemLst.Remove(ItemLst[i]);
                }
            }
            Session["ItemList"] = null;

            if (ItemLst.Count > 0)
            {
                Session["ItemList"] = ItemLst;
            }
            else
            {
                Session["ItemList"] = new List<GQIInfo>();
            }

            return Json(Session["ItemList"], JsonRequestBehavior.AllowGet);
        }
        #endregion

        // GET: GoodQualityInspections/Create
        public ActionResult Create()
        {
            ViewBag.GRNId = new SelectList(db.GRNmanagement, "Id", "GRNNumber");
            ViewBag.CreatedBy = new SelectList(db.User, "Id", "Name");
            Session["ItemList"] = new List<GQIInfo>();
            return View();
        }

        // POST: GoodQualityInspections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Sequence,GRNId,CreatedBy")] GoodQualityInspection goodQualityInspection)
        {
            List<GQIInfo> ItemLst = new List<GQIInfo>();
            ItemLst = (List<GQIInfo>)Session["ItemList"];
            if (ItemLst.Count >0)
            {
                goodQualityInspection.InspectionDate = DateTime.Now.Date;
                goodQualityInspection.CreatedBy = Convert.ToInt32(Session["ADMINID"]);
                db.GoodQualityInspection.Add(goodQualityInspection);
                db.SaveChanges();

                #region Add Details
                List<GQIInfo> ItemList = new List<GQIInfo>();
                ItemList = (List<GQIInfo>)Session["ItemList"];

                for (int i = 0; i < ItemList.Count; i++)
                {
                    GQIInfo details = new GQIInfo();
                    details.ItemId = ItemList[i].ItemId;
                    details.ReceivedQuantity = ItemList[i].ReceivedQuantity;
                    details.QCPassedQuantity = ItemList[i].QCPassedQuantity;
                    details.RejectedQuantity = ItemList[i].RejectedQuantity;
                    details.StoreId = ItemList[i].StoreId;
                    Store store = db.Store.Find(ItemList[i].StoreId);
                    store.Status = false;
                    details.GQIId = goodQualityInspection.Id;
                    db.GQIInfo.Add(details);
                    db.SaveChanges();
                }
                //for (int i = 0; i < ItemList.Count; i++)
                //{
                //    Store store = db.Store.Where(a => a.Id == ItemList[i].StoreId).FirstOrDefault();
                //    store.Status = false;
                // }
                #endregion

                return RedirectToAction("Index");
            }

            ViewBag.GRNId = new SelectList(db.GRNmanagement, "Id", "GRNNumber", goodQualityInspection.GRNId);
            ViewBag.CreatedBy = new SelectList(db.User, "Id", "Name", goodQualityInspection.CreatedBy);
            return View(goodQualityInspection);
        }

        // GET: GoodQualityInspections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodQualityInspection goodQualityInspection = db.GoodQualityInspection.Find(id);
            if (goodQualityInspection == null)
            {
                return HttpNotFound();
            }
            ViewBag.GRNId = new SelectList(db.GRNmanagement, "Id", "GRNNumber", goodQualityInspection.GRNId);
            ViewBag.CreatedBy = new SelectList(db.User, "Id", "Code", goodQualityInspection.CreatedBy);
            return View(goodQualityInspection);
        }

        // POST: GoodQualityInspections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Sequence,GRNId,CreatedBy")] GoodQualityInspection goodQualityInspection)
        {
            if (ModelState.IsValid)
            {
                db.Entry(goodQualityInspection).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GRNId = new SelectList(db.GRNmanagement, "Id", "GRNNumber", goodQualityInspection.GRNId);
            ViewBag.CreatedBy = new SelectList(db.User, "Id", "Code", goodQualityInspection.CreatedBy);
            return View(goodQualityInspection);
        }

        // GET: GoodQualityInspections/Delete/5
        public ActionResult Delete(int? id)
        {

StoreManagementSystem/Views/GoodQualityInspections/Delete.cshtml
@model StoreManagementSystem.Models.GoodQualityInspection

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GoodQualityInspection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GRN.GRNType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GRN.GRNType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sequence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sequence)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoreManagementSystem/Views/GoodQualityInspections/Details.cshtml
@model StoreManagementSystem.Models.GoodQualityInspection

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>GoodQualityInspection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GRN.GRNType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GRN.GRNType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sequence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sequence)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InspectionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InspectionDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoreManagementSystem/Views/GoodQualityInspections/Edit.cshtml
@model StoreManagementSystem.Models.GoodQualityInspection

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GoodQualityInspection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Sequence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sequence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GRNId, "GRNId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GRNId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GRNId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, "CreatedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreatedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StoreManagementSystem/Views/GoodQualityInspections/GoodQualityInspectionByDateRange.cshtml
@{
    ViewBag.Title = "GoodQualityInspetionByDateRange";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var GQIInfoDetailsList = (List<StoreManagementSystem.Models.GQIInfo>)Session["GQIDetailsList"];
}
<br />
<h2>Good Quality Inspection By Date Range</h2>
<br />
@using (Html.BeginForm("GoodQualityInspectionByDateRangeView", "GoodQualityInspections"))
{
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <div class="controls">
                    <input type="date" id="from_date" name="FromDate" placeholder="From Date" class="form-control datepicker" data-start-view="2" required>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div class="controls">
                    <input type="date" id="to_date" name="ToDate" placeholder="To Date" class="form-control datepicker" data-start-view="2" required>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
    <hr />
    <div class="content-body">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="table-responsive" data-pattern="priority-columns">
                    @if (Model.Count > 0)
                    {
                        <div class="btn-group">
                            @using (Html.BeginForm("PrintGoodQualityInspectionByDateRangeByDateRange", "TransferRequisitionIssues", FormMethod.Post, new { @target = "_blank", @role = "form", @enctype = "multipart/form-data" }))
                            {
                                <button type="button" onclick="location.href='@Url.Action("PrintGoodQualityInspectionByDateRangeByDateRange", "GoodQualityInspections")'" target="_blank" class="btn btn-info btn-sm">
                                    <span class="glyphicon glyphicon-print"></span> Print
                                </button>
                            }
                        </div>

                        <div>
                            @foreach (var item in Model)
                            {
                                <hr />
                                <h4>Good Quality Inspection ID: @item.Id</h4>
                                <h4>Sequence : @item.Sequence</h4>
                                <h4>Inspection date : @item.InspectionDate</h4>
                                <h4>GRN Id : @item.GRNId</h4>
                                {
                                    <table cellspacing="0" id="tech-companies-1" class="table table-small-font table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th data-priority="1" style="text-align:center">Item</th>
                                                <th data-priority="1" style="text-align:center">Received Quanitity</th>
                                                <th data-priority="1" style="text-align:center">QC Passed Quantity</th>
                                                <th data-priority="1" style="text-align:center">Rejected Quantity</th>
                                                <th data-priority="1" style="text-align:center">Store Name</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var itm in GQIInfoDetailsList)
                                            {
                                                if (itm.GQIId == item.Id)
                                                {
                                                    <tr>
                                                        <td align="center">@itm.Item.Name</td>
                                                        <td align="center">@itm.ReceivedQuantity</td>
                                                        <td align="center">@itm.QCPassedQuantity</td>
                                                        <td align="center">@itm.RejectedQuantity</td>
                                                        <td align="center">@itm.Store.Name</td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                }
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

StoreManagementSystem/Views/GoodQualityInspections/Index.cshtml
@model IEnumerable<StoreManagementSystem.Models.GoodQualityInspection>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<br />
<div class="col-md-12 col-sm-12 col-xs-12">
    @{int rowNo = 0;}
    <table id="myTable" class="table table-striped dt-responsive display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>SL</th>
                <th>
                    Details
                </th>
                <th>
                    GRN Type
                </th>
                <th>
                    Created By
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sequence)
                </th>
                <th>
                    Inspection Date
                </th>
                <th>Options</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>SL</th>
                <th>
                    Details
                </th>
                <th>
                    GRN Type
                </th>
                <th>
                    Created By
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sequence)
                </th>
                <th>
                    Inspection Date
                </th>
                <th>Options</th>
            </tr>
        </tfoot>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td align="center" width="5%">
                        @(rowNo += 1)
                    </td>
                    <td align="center" width="8%">
                        <button type="button" class="btn btn-default btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "GQIInfoes", new { id = item.Id })'">Item Details</button>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GRN.GRNType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sequence)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InspectionDate)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section content
{
    @Styles.Render("~/Content/dataTable")
}
@section scripts
{
    @Scripts.Render("~/bundles/dataTable")
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': true,
                'processing': true
            });
        });
    </script>
}

StoreManagementSystem/Views/GoodQualityInspections/PrintGoodQualityInspectionByDateRangeByDateRange.cshtml
@model IEnumerable<StoreManagementSystem.Models.GoodQualityInspection>
@{
    ViewBag.Title = "PrintGoodQualityInspectionByDateRange";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var GQIDetailsList = (List<StoreManagementSystem.Models.GQIInfo>)Session["GQIDetailsList"];
}

<script src="~/Content/jquery-1.11.2.min.js" type="text/javascript"></script>
<head>
    <meta charset="utf-8">
    <title>Good Quality Inspection</title>
    <link rel="stylesheet" href="style.css" media="all" />
</head>

<header class="clearfix">
    <h1>Good Quality Inspection List</h1>
</header>


<body>
    <main>
        <div class="content-body">
            <div class="table-responsive" data-pattern="priority-columns">
                <div class="form-group" display="inline">
                    <div style="float: left; width: 100%">
                        <div>
                            @foreach (var item in Model)
                            {
                                <hr />
                                <h4>Good Quality Inspection ID: @item.Id</h4>
                                <h4>Sequence : @item.Sequence</h4>
                                <h4>Inspection date : @item.InspectionDate</h4>
                                <h4>GRN Id : @item.GRNId</h4>
                                {
                                    <table cellspacing="0" id="tech-companies-1" class="table table-small-font table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th data-priority="1" style="text-align:center">Item</th>
                                                <th data-priority="1" style="text-align:center">Received Quanitity</th>
                                                <th data-priority="1" style="text-align:center">QC Passed Quantity</th>
                                                <th data-priority="1" style="text-align:center">Rejected Quantity</th>
                                                <th data-priority="1" style="text-align:center">Store Name</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var itm in GQIDetailsList)
                                            {
                                                if (itm.GQIId == item.Id)
                                                {
                                                    <tr>
                                                        <td align="center">@itm.Item.Name</td>
                                                        <td align="center">@itm.ReceivedQuantity</td>
                                                        <td align="center">@itm.QCPassedQuantity</td>
                                                        <td align="center">@itm.RejectedQuantity</td>
                                                        <td align="center">@itm.Store.Name</td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="notices">
            <div>Good Quality Inspection Information</div>
            <div class="notice">This is date wise record of your Good Quality Inspection information</div>
        </div>
    </main>
</body>
<footer style="margin-top:20%">
    <p class="text-center">Copyrights &#169; 2018 Setu. All Rights Reserved.</p>
</footer>



<style>
    .square {
        border-radius: 4px;
        background: #228B22;
        width: 60%;
        height: 10%;
        text-align: center;
        margin-left: 25%;
        font-size: 30px;
    }

        .square b {
            color: #fff;
            text-align: center;
        }

    .square2 {
        border-radius: 4px;
        background: #ff0000;
        width: 60%;
        height: 10%;
        text-align: center;
        margin-left: 25%;
        font-size: 25px;
    }

        .square2 b {
            color: #fff;
            text-align: center;
        }

    .square3 {
        border-radius: 4px;
        background: #002366;
        width: 110%;
        height: 10%;
        text-align: center;
        font-size: 25px;
        margin-left: 15%;
    }

        .square3 b {
            color: #fff;
            text-align: center;
        }


    .clearfix:after {
        content: "";
        display: table;
        clear: both;
    }

    a {
        color: #5D6975;
        text-decoration: underline;
    }

    body {
        position: relative;
        width: 21cm;
        margin: 0 auto;
        color: #001028;
        background: #FFFFFF;
        font-family: Arial, sans-serif;
        font-size: 12px;
    }

    header {
        padding: 10px 0;
    }

    #logo {
        text-align: center;
        margin-bottom: 10px;
    }

        #logo img {
            width: 100%;
        }

    h1 {
        border-top: 1px solid #5D6975;
        border-bottom: 1px solid #5D6975;
        color: #5D6975;
        font-size: 2.4em;
        line-height: 1.4em;
        font-weight: normal;
        text-align: center;
        margin: 0 0 20px 0;
        background: url(dimension.png);
    }

    #project {
        float: left;
    }

        #project span {
            color: #5D6975;
            text-align: right;
            width: 52px;
            margin-right: 10px;
            display: inline-block;
            font-size: 0.8em;
        }

    #company {
        float: right;
        text-align: right;
    }

    #status {
        margin-top: 3%;
    }


    #project div,
    #company div {
        white-space: nowrap;
        font-size: 12px;
    }

    table {
        width: 50%;
        border-collapse: collapse;
        border-spacing: 0;
        margin-bottom: 20px;
    }

        table tr:nth-child(2n-1) td {
            background: #F5F5F5;
        }

        table th,
        table td {
            text-align: center;
        }

        table th {
            padding: 5px 20px;
            color: #5D6975;
            border-bottom: 1px solid #C1CED9;
            white-space: nowrap;
            font-weight: normal;
        }

        table .service,
        table .desc {
            text-align: left;
        }

        table td {
            padding: 20px;
            text-align: center;
        }

            table td.service,
            table td.desc {
                vertical-align: top;
            }

            table td.unit,
            table td.qty,
            table td.total {
                font-size: 1.2em;
            }

            table td.grand {
                border-top: 1px solid #5D6975;
            }

    #notices .notice {
        color: #5D6975;
        font-size: 1.2em;
    }
</style>