StoreManagementSystem/Models/PurchaseOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace StoreManagementSystem.Models
{
    public class PurchaseOrder
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Select Requisition")]
        [ForeignKey("Requisition")]
        public int ReqNoId { get; set; }

        public int PurchaseOrderNo { get; set; }

        [DataType(DataType.Date),
        DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}",
        ApplyFormatInEditMode = true)]
        public DateTime PurchaseOrderDate { get; set; }

        [Required(ErrorMessage ="Select Delivery")]
        [ForeignKey("Delivery")]
        public int DeliveryId { get; set; }

        [Required(ErrorMessage ="Select Bill to")]
        [ForeignKey("Billto")]
        public int BillToId { get; set; }

        [Required(ErrorMessage ="Select marketing person")]
        [ForeignKey("MKTPerson")]
        public int MKTPersonId { get; set; }

        [Required(ErrorMessage ="Select currency")]
        [StringLength(20)]
        public string Currency { get; set; }

        [StringLength(10)]
        public string CurrencyRate { get; set; }

        [StringLength(100)]
        public string PaymentTerm { get; set; }

        [Required(ErrorMessage ="Select Shipping method")]
        public string Shipedby { get; set; }

        [StringLength(100)]
        public string TradeTerm { get; set; }

        [StringLength(200)]
        public string Note { get; set; }

        [DefaultValue(true)]
        public bool Status { get; set; }

        public virtual PRM Requisition { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual BillTo Billto { get; set; }
        public virtual MKTPerson MKTPerson { get; set; }

    }
}

StoreManagementSystem/Controllers/PurchaseOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreManagementSystem.Models;

namespace StoreManagementSystem.Controllers
{
    public class PurchaseOrdersController : Controller
    {
        private SMSDbContext db = new SMSDbContext();

        // GET: PurchaseOrders
        public ActionResult Index()
        {
            var purchaseOrder = db.PurchaseOrder.Include(p => p.Billto).Include(p => p.Delivery).Include(p => p.MKTPerson).Include(p => p.Requisition);
            return View(purchaseOrder.ToList());
        }

        // GET: PurchaseOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseOrder purchaseOrder = db.PurchaseOrder.Find(id);
            if (purchaseOrder == null)
            {
                return HttpNotFound();
            }
            return View(purchaseOrder);
        }

        public ActionResult GetExistingItems()
        {
            string ItemName = Request["ItemName"];
            int ReqId = Convert.ToInt32(Request["reqId"]);
            List<PRMDetails> ItemList = new List<PRMDetails>();
            if (String.IsNullOrWhiteSpace(ItemName))
            {
                ItemList = db.PRMDetails.Where(i => i.PRMId == ReqId && i.Status == true).ToList();
            }
            else
            {
                ItemList = db.PRMDetails.Where(i => i.PRMId == ReqId && i.Status == true).Where(i => i.Item.Name.Contains(ItemName)).ToList();
            }
            return Json(ItemList, JsonRequestBehavior.AllowGet);
        }

        #region GetSelectedItems
        [AllowAnonymous]
        [HttpPost]
        public ActionResult GetSelectedItems()
        {
            if (Request["ItemId"].ToString() != "")
            {
                int ItemId = Convert.ToInt32(Request["ItemId"]);
                double Price = Convert.ToDouble(Request["Price"]);
                double Quantity = Convert.ToDouble(Request["Quantity"]);
                double Total = Convert.ToDouble(Request["Total"]);
                int SupplierId = Convert.ToInt32(Request["SupplierId"]);

                List<PurchaseOrderDetails> ItemList = new List<PurchaseOrderDetails>();
                ItemList = (List<PurchaseOrderDetails>)Session["ItemList"];
                if (ItemList.Count() > 0)
                {
                    PurchaseOrderDetails details = new PurchaseOrderDetails();
                    details.Id = ItemList.Count() + 1;
                    details.ItemId = ItemId;
                    details.Price = Price;
                    details.Quantity = Quantity;
                    details.TotalPrice = Total;
                    details.SuppierId = SupplierId;
                    details.Item = db.Item.Find(ItemId);
                    details.Supplier = db.Supplier.Find(SupplierId);
                    ItemList.Add(details);
                    Session["ItemList"] = ItemList;
                }
                else
                {
                    List<PurchaseOrderDetails> ItemLst = new List<PurchaseOrderDetails>();
                    PurchaseOrderDetails details = new PurchaseOrderDetails();
                    details.Id = 1;
                    details.ItemId = ItemId;
                    details.Price = Price;
                    details.Quantity = Quantity;
                    details.TotalPrice = Total;
                    details.SuppierId = SupplierId;
                    details.Item = db.Item.Find(ItemId);
                    details.Supplier = db.Supplier.Find(SupplierId);
                    ItemLst.Add(details);
                    Session["ItemList"] = ItemLst;
                }
            }
            return Json(Session["ItemList"], JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult DeleteFromList()
        {
            int DetailsId = Convert.ToInt32(Request["DetailsId"]);
            List<PurchaseOrderDetails> ItemLst = new List<PurchaseOrderDetails>();
            ItemLst = (List<PurchaseOrderDetails>)Session["ItemList"];
            for (int i = 0; i < ItemLst.Count; i++)
            {
                if (ItemLst[i].Id == DetailsId)
                {
                    ItemLst.Remove(ItemLst[i]);
                }
            }
            Session["ItemList"] = null;

            if (ItemLst.Count > 0)
            {
                Session["ItemList"] = ItemLst;
            }
            else
            {
                Session["ItemList"] = new List<PurchaseOrderDetails>();
            }

            return Json(Session["ItemList"], JsonRequestBehavior.AllowGet);
        }
        #endregion

        // GET: PurchaseOrders/Create
        public ActionResult Create()
        {
            if (db.PurchaseOrder.Count() > 0)
            {
                ViewBag.PurchaseOrderNo = db.PurchaseOrder.Max(i => i.PurchaseOrderNo) + 1;
            }
            else
            {
                ViewBag.PurchaseOrderNo = 1;
            }
            ViewBag.BillToId = new SelectList(db.BillTo, "Id", "Name");
            ViewBag.DeliveryId = new SelectList(db.Delivery, "Id", "Name");
            ViewBag.MKTPersonId = new SelectList(db.MKTPerson, "Id", "Name");
            ViewBag.ReqNoId = new SelectList(db.PRM.Where(i => i.Status == true), "Id", "ReqNo");
            ViewBag.SupplierId = new SelectList(db.Supplier, "Id", "Name");
            Session["ItemList"] = new List<PurchaseOrderDetails>();
            return View();
        }

        // POST: PurchaseOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ReqNoId,PurchaseOrderNo,PurchaseOrderDate,SupplierId,DeliveryId,BillToId,MKTPersonId,Currency,CurrencyRate,PaymentTerm,Shipedby,TradeTerm,Note")] PurchaseOrder purchaseOrder)
        {
            List<PurchaseOrderDetails> ItemLst = new List<PurchaseOrderDetails>();
            ItemLst = (List<PurchaseOrderDetails>)Session["ItemList"];
            if (ItemLst.Count > 0)
            {
                purchaseOrder.PurchaseOrderDate = DateTime.Now.Date;
                purchaseOrder.Status = true;
                db.PurchaseOrder.Add(purchaseOrder);
                db.SaveChanges();

                #region Add Details
                List<PurchaseOrderDetails> ItemList = new List<PurchaseOrderDetails>();
                ItemList = (List<PurchaseOrderDetails>)Session["ItemList"];

                for (int i = 0; i < ItemList.Count; i++)
                {
                    PurchaseOrderDetails details = new PurchaseOrderDetails();
                    details.ItemId = ItemList[i].ItemId;
                    details.Price = ItemList[i].Price;
                    details.Quantity = ItemList[i].Quantity;
                    details.TotalPrice = ItemList[i].TotalPrice;
                    details.SuppierId = ItemList[i].SuppierId;
                    details.PurchaseOrderId = purchaseOrder.Id;
                    db.PurchaseOrderDetails.Add(details);
                    db.SaveChanges();

                    int prmDetailsId = db.PRMDetails.Where(x => x.PRMId == purchaseOrder.ReqNoId && x.ItemId == details.ItemId).Select(x => x.Id).FirstOrDefault();
                    PRMDetails prmDetails = db.PRMDetails.Find(prmDetailsId);
                    prmDetails.Status = false;
                    db.Entry(prmDetails).State = EntityState.Modified;
                    db.SaveChanges();
                }

                if(db.PRMDetails.Where(i=> i.PRMId == purchaseOrder.ReqNoId && i.Status == true).ToList().Count == 0)
                {
                    PRM prm = db.PRM.Find(purchaseOrder.ReqNoId);
                    prm.Status = false;
                    db.Entry(prm).State = EntityState.Modified;
                    db.SaveChanges();
                }
                #endregion

                return RedirectToAction("Index");
            }

            ViewBag.BillToId = new SelectList(db.BillTo, "Id", "Name", purchaseOrder.BillToId);
            ViewBag.DeliveryId = new SelectList(db.Delivery, "Id", "Name", purchaseOrder.DeliveryId);
            ViewBag.MKTPersonId = new SelectList(db.MKTPerson, "Id", "Name", purchaseOrder.MKTPersonId);
            ViewBag.ReqNoId = new SelectList(db.PRM.Where(i=> i.Status == true), "Id", "Name", purchaseOrder.ReqNoId);
            return View(purchaseOrder);
        }

        // GET: PurchaseOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseOrder purchaseOrder = db.PurchaseOrder.Find(id);
            if (purchaseOrder == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillToId = new SelectList(db.BillTo, "Id", "Name", purchaseOrder.BillToId);
            ViewBag.DeliveryId = new SelectList(db.Delivery, "Id", "Name", purchaseOrder.DeliveryId);
            ViewBag.MKTPersonId = new SelectList(db.MKTPerson, "Id", "Name", purchaseOrder.MKTPersonId);
            ViewBag.ReqNoId = new SelectList(db.PRM.Where(i => i.Status == true), "Id", "Note", purchaseOrder.ReqNoId);
            return View(purchaseOrder);
        }

        // POST: PurchaseOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

StoreManagementSystem/Views/PurchaseOrders/Delete.cshtml
@model StoreManagementSystem.Models.PurchaseOrder

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PurchaseOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Billto.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Billto.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MKTPerson.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MKTPerson.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Requisition.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Requisition.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseOrderNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseOrderNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseOrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseOrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentTerm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shipedby)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipedby)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TradeTerm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TradeTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoreManagementSystem/Views/PurchaseOrders/Details.cshtml
@model StoreManagementSystem.Models.PurchaseOrder

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PurchaseOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Bill To
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Billto.Name)
        </dd>

        <dt>
            Delivery To
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Name)
        </dd>

        <dt>
            Marketing Person
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MKTPerson.Name)
        </dd>

        <dt>
            Requisition Note
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Requisition.ReqNo)
        </dd>

        <dt>
            Purchase Order No
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseOrderNo)
        </dd>

        <dt>
            Purchase Order Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseOrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            Currency Rate
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyRate)
        </dd>

        <dt>
            Payment Term
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentTerm)
        </dd>

        <dt>
            Shipped By
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipedby)
        </dd>

        <dt>
            Trade Term
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TradeTerm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoreManagementSystem/Views/PurchaseOrders/Edit.cshtml
@model StoreManagementSystem.Models.PurchaseOrder

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PurchaseOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ReqNoId, "ReqNoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ReqNoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReqNoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseOrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseOrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseOrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseOrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseOrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseOrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierId, "SupplierId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupplierId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryId, "DeliveryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeliveryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeliveryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillToId, "BillToId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BillToId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BillToId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MKTPersonId, "MKTPersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MKTPersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MKTPersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Currency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrencyRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrencyRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentTerm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentTerm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentTerm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Shipedby, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shipedby, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Shipedby, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TradeTerm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TradeTerm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TradeTerm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StoreManagementSystem/Views/PurchaseOrders/PurchaseOrderByDateRange.cshtml
@{
    ViewBag.Title = "PurchaseOrderByDateRange";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var PurchaseOrderDetailsList = (List<StoreManagementSystem.Models.PurchaseOrderDetails>)Session["PurchaseOrderDetailsList"];
}
<br />
<h2>Purchase Order By Date Range</h2>
<br />
@using (Html.BeginForm("PurchaseOrderByDateRangeView", "PurchaseOrders"))
{
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <div class="controls">
                    <input type="date" id="from_date" name="FromDate" placeholder="From Date" class="form-control datepicker" data-start-view="2" required>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div class="controls">
                    <input type="date" id="to_date" name="ToDate" placeholder="To Date" class="form-control datepicker" data-start-view="2" required>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
    <hr />
    <div class="content-body">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="table-responsive" data-pattern="priority-columns">
                    @if (Model.Count > 0)
                    {
                        <div class="btn-group">
                            @using (Html.BeginForm("PrintPurchaseOrderByDateRange", "PurchaseOrders", FormMethod.Post, new { @target = "_blank", @role = "form", @enctype = "multipart/form-data" }))
                            {
                                <button type="button" onclick="location.href='@Url.Action("PrintPurchaseOrderByDateRange", "PurchaseOrders")'" target="_blank" class="btn btn-info btn-sm">
                                    <span class="glyphicon glyphicon-print"></span> Print
                                </button>
                            }
                        </div>

                        <div>
                            @foreach (var item in Model)
                            {
                                <hr />
                                <h4>Purchase Order ID: @item.Id</h4>
                                <h4>Purchase Order No: @item.PurchaseOrderNo</h4>
                                <h4>Requisition No: @item.Requisition.ReqNo</h4>
                                <h4>Purchase Order Date: @item.PurchaseOrderDate</h4>
                                <h4>Marketing Person: @item.MKTPerson.Name</h4>
                                {
                                    <table cellspacing="0" id="tech-companies-1" class="table table-small-font table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th data-priority="1" style="text-align:center">Item</th>
                                                <th data-priority="1" style="text-align:center">Quantity</th>
                                                <th data-priority="1" style="text-align:center">Price</th>
                                                <th data-priority="1" style="text-align:center">Total Price</th>
                                                <th data-priority="1" style="text-align:center">Supplier</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var itm in PurchaseOrderDetailsList)
                                            {
                                                if (itm.PurchaseOrderId == item.Id)
                                                {
                                                    <tr>
                                                        <td align="center">@itm.Item.Name</td>
                                                        <td align="center">@itm.Quantity</td>
                                                        <td align="center">@itm.Price</td>
                                                        <td align="center">@itm.TotalPrice</td>
                                                        <td align="center">@itm.Supplier.Name</td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                }
                            }
                        </div>                        
                    }
                </div>
            </div>
        </div>
    </div>
}